### ISSUE TITLE
Documentation - README.md

### ISSUE THREAD

**Issue by dvfrancis** [Ant2210/diverseDevs#6]
Write the README.md file.

**Comment by dvfrancis** [comment]
I have written the user stories, and will add them to the README.md file.

**Comment by dvfrancis** [comment]
User stories added to the readme, along with some other info. I want to add some images to the readme, but need to wait until my previous pull requests have been approved.

**Comment by dvfrancis** [comment]
Previous pull requests approved - changes now made.

**Comment by dvfrancis** [comment]
Rob and I have added further details to the readme. Awaiting feedback and suggestions for additions, as the project moves toward completion.

**Comment by SarahA79** [comment]
Hey guys, can someon add in the Deployment info as and when its set up please?
